language: objective-c

before_install:
  - brew update
  - brew upgrade xctool
  
notifications:
  webhooks: http://progress.flatironschool.com/submissions

script: xctool -reporter json-stream -workspace EpochButton/EpochButton.xcworkspace -sdk iphonesimulator -scheme EpochButton build test
